### ISSUE TITLE
Install NX globally

### ISSUE THREAD

**Issue by Tambouil** [moonrepo/proto#60]
I'm trying to install NX monorepo CLI globally on my machine but it's not working when node is installed with proto.

With Volta you can do this `Volta install NX`

**Comment by milesj** [comment]
@Tambouil What command are you trying to run? It would just be `npm install -g nx` with proto.

**Comment by Tambouil** [comment]
> @Tambouil What command are you trying to run? It would just be `npm install -g nx` with proto.

this is the command I tried to run and I get `zsh: command not found: nx` even after restart.

**Comment by milesj** [comment]
Actually your right, the path handling is wrong here.

This is actually quite difficult with proto because all these tools install globals in different locations, and since proto is multi-tool, it has the change of global names colliding. I may have to build a custom solution here that standardizes all of them.

**Comment by Tambouil** [comment]
Ok thank you ! I will keep an eye on updates

**Comment by milesj** [comment]
Working on this now. Hopefully a day or 2.
